export default [
  {
    id: 'H1',
    image: require('../assets/House1.jpeg'),
    name: 'My First House',
    totalRooms: 11,
    remainingRooms: 4,
    address: '1655/30, L Block, Shani Bazar Road, Sangam Vihar, New Delhi - 11080',
  },
  {
    id: 'H2',
    image: require('../assets/House2.jpg'),
    name: 'My Second House',
    totalRooms: 5,
    remainingRooms: 4,
    address: '1655/30, L Block, Shani Bazar Road, Sangam Vihar, New Delhi - 11080',
  },
  {
    id: 'H3',
    image: require('../assets/House3.jpg'),
    name: 'My Third House',
    totalRooms: 8,
    remainingRooms: 1,
    address: '1655/30, L Block, Shani Bazar Road, Sangam Vihar, New Delhi - 11080',
  },
  {
    id: 'H4',
    image: require('../assets/House4.jpg'),
    name: 'My Forth House',
    totalRooms: 16,
    remainingRooms: 12,
    address: '1655/30, L Block, Shani Bazar Road, Sangam Vihar, New Delhi - 11080',
  },
  {
    id: 'H5',
    image: require('../assets/House5.jpg'),
    name: 'My Fifth House',
    totalRooms: 1,
    remainingRooms: 0,
    address: '1655/30, L Block, Shani Bazar Road, Sangam Vihar, New Delhi - 11080',
  },
];
